### ISSUE TITLE
Option to label segments visually

### ISSUE THREAD

**Issue by sethcohn** [scherroman/mugen#11]
I know new_mugen doesn't have 'recreate' yet, or even the json file, like 'original' mugen, but before I forget, cause I realized how much time this would save me...

How I review my generated video now: make a video, watch the video, realize I dislike a number of random clips used, and want to replace them, and now I have to recreate the video with some changes.  So I have to figure out which clips they are.  If I save segments, I can go in and find the videos manually, and this works... but it's annoying, I have to look at hundreds of thumbnails sometimes, and pick out the ones I dislike and try again...

It would be nice to have a way to generate 'debugging' videos where the clips are labeled with what # they are, so I could just pause the video and note the number, and then recreate telling it to replace that # (or #s)?  And once I'm happy with the resulting videos, recreate without that debugging and the final video will be pristine, but no need to keep saving segments over and over?

Adding a text overlay in the upper corner (or whatever location) with the clip number should be a fairly trivial tweak, right?

**Comment by sethcohn** [comment]
pseudocode for moviepy to do this should look like:
text = TextClip("clip#", fontoptions).set_pos("left","top")
clip = VideoFileClip(selected movie location and duration details)
final_clip = CompositeVideoClip([clip, textclip])

**Comment by scherroman** [comment]
Actually, if you open up any of the music videos created by old mugen after commit 701179b, you should find some subtitle tracks, one of which shows the clip numbers. You should also find an extra audio track with the overlaid preview bleeps. I never properly documented that. New mugen doesn't have it yet, but i'll add it in again next commit likely.

I'd been down that road as well, and looked into moviepy's TextClips at first, but they required the addition of a new external dependency, which was a no no. So I used ffmpeg to add in the extra subtitle/audio tracks.
