### ISSUE TITLE
Feature Request - Fade in, Fade out

### ISSUE THREAD

**Issue by sethcohn** [scherroman/mugen#13]
Even in your sample video at https://www.youtube.com/watch?v=lHgFYo37CaU
It would greatly benefit from a simple fade in from black at the start, and fade out from black at the end, to match the audio better.  A simple "--fadein 2" or "--fadeout 2" would allow customizing this and avoid the 'loose ends' that exist now from the beat matching...

**Comment by scherroman** [comment]
You're quite right. That's actually an easy one to implement via moviepy if we just do it via manual options like "--fadein" and "--fadeout".

Just so you know haha, that video is actually from the early days of old mugen. I liked it a lot though. 

With my latest commit a781a5d, those loose ends from rough beat detection should be easily correctable. The updated readme examples should guide you in the right direction.
