### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by kingsofcoms** [scherroman/mugen#16]
I cannot get it to install, I've tried running the code on Windows 7 and Ubuntu 16.04. I get the same error

K:\mugen>conda env create -f environment.yml
Fetching package metadata ...........
Solving package specifications: .
Collecting cython>=0.25.2
  Using cached Cython-0.26-cp36-none-win_amd64.whl
Collecting moviepy>=0.2.3.2
  Using cached moviepy-0.2.3.2-py2.py3-none-any.whl
Collecting librosa>=0.5.0
  Using cached librosa-0.5.1.tar.gz
Collecting Pillow>=3.4.2
  Using cached Pillow-4.2.1-cp36-cp36m-win_amd64.whl
Collecting numpy>=1.12.0
  Using cached numpy-1.13.1-cp36-none-win_amd64.whl
Collecting pysrt>=1.1.1
  Using cached pysrt-1.1.1.tar.gz
Collecting tqdm>=4.10.0
  Using cached tqdm-4.15.0-py2.py3-none-any.whl
Collecting decorator>=4.0.11
  Using cached decorator-4.1.2-py2.py3-none-any.whl
Collecting dill>=0.2.7.1
  Using cached dill-0.2.7.1.tar.gz
Collecting imageio==2.1.2 (from moviepy>=0.2.3.2)
  Using cached imageio-2.1.2.zip
Collecting audioread>=2.0.0 (from librosa>=0.5.0)
  Using cached audioread-2.1.5.tar.gz
Collecting scipy>=0.13.0 (from librosa>=0.5.0)
  Using cached scipy-0.19.1.tar.gz
Collecting scikit-learn>=0.14.0 (from librosa>=0.5.0)
  Using cached scikit_learn-0.19.0-cp36-cp36m-win_amd64.whl
Collecting joblib>=0.7.0 (from librosa>=0.5.0)
  Using cached joblib-0.11-py2.py3-none-any.whl
Collecting six>=1.3 (from librosa>=0.5.0)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting resampy>=0.1.2 (from librosa>=0.5.0)
  Using cached resampy-0.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\SamM\AppData\Local\Temp\pip-build-18o9g51f\resampy\setup.p
y", line 6, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\SamM\Ap
pData\Local\Temp\pip-build-18o9g51f\resampy\

CondaValueError: pip returned an error.

**Comment by kingsofcoms** [comment]
This happens when I try to install librosa

K:\mugen>pip install librosa
Collecting librosa
Requirement already satisfied: six>=1.3 in c:\users\xxxx\appdata\local\programs
\python\python36-32\lib\site-packages (from librosa)
Collecting audioread>=2.0.0 (from librosa)
Collecting scipy>=0.13.0 (from librosa)
  Using cached scipy-0.19.1.tar.gz
Collecting numpy>=1.8.0 (from librosa)
  Using cached numpy-1.13.1-cp36-none-win32.whl
Collecting decorator>=3.0.0 (from librosa)
  Using cached decorator-4.1.2-py2.py3-none-any.whl
Collecting joblib>=0.7.0 (from librosa)
  Using cached joblib-0.11-py2.py3-none-any.whl
Collecting scikit-learn>=0.14.0 (from librosa)
  Downloading scikit_learn-0.19.0-cp36-cp36m-win32.whl (3.9MB)
    100% |████████████████████████████████| 3.9MB 202kB/s
Collecting resampy>=0.1.2 (from librosa)
  Using cached resampy-0.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xxxx\AppData\Local\Temp\pip-build-r70crwal\resampy\setup.p
y", line 6, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\xxxx\Ap
pData\Local\Temp\pip-build-r70crwal\resampy\

**Comment by sethcohn** [comment]
Install just numpy first.  I found similar weirdness but once installed, things worked right.

**Comment by scherroman** [comment]
Seth is right, for the time being this seems to be an [ongoing issue](https://github.com/librosa/librosa/issues/533) with the pip install of librosa due to its dependency on resampy. I'm currently working on a commit to make mugen pip-installable, but I'll also experiment with the conda install of librosa to see if this hiccup can be avoided when installing using mugen's conda environment.

**Comment by kingsofcoms** [comment]
I have been trying installing for 3 days now, also looking for answers, no luck. This is not mugen issue but general resampy/librosa/scipy issue, I've also tried to install this github.com/kazuar/got_remix project to see if it works, but it fails to install. I'll keep trying and post update if i find a solution.

**Comment by kingsofcoms** [comment]
I am getting error: No module named 'bin'
(mugen) F:\mugen\src\bin>python cli.py --help
**Traceback (most recent call last):
  File "cli.py", line 9, in <module>
    import bin.constants as cli_c
ModuleNotFoundError: No module named 'bin'**

![Conda List and bin error](http://i.imgur.com/xpomlQX.png)

**Comment by kingsofcoms** [comment]
ok i fixed this by adding **sys.path.append("../")** to cli.py and utility.py

**Comment by kingsofcoms** [comment]
How long does a conversion take? The audio beat preview is working fine, but 5min video and 3min audio is taking too long, i kept it going for more than an hour, also i tried reducing the beat. It just keeps executing. My CPU is AMD Fx6300 Six core 3.5Ghz.

**Comment by scherroman** [comment]
This should be documented better, but one of the built-in filters is to discard repeats. 5 min of video could be too little to use depending on the bpm of the music. Try using more/longer videos, or otherwise try using --exclude-video-filters not_is_repeat

**Comment by kingsofcoms** [comment]
thank you, changing the length seems to work (tried it on a movie). Also the above filters work for 5min video but has lots of repeats. In both cases it took no longer than 8minutes.

**Comment by kingsofcoms** [comment]
is there a way to export the detected parts in several clips instead of the main video, clips length will be based on bpm.

**Comment by scherroman** [comment]
You can use the --save-segments option to save the individual clips that make up the music video. 

As for your issue earlier with needing to use sys.path.append("../") to use the command line interface, I'm aware of this and it should be solved once I push my commit for installing mugen via pip.

Please forgive the rough state of the installation and the documentation, the project is still being organized, and usability will definitely improve over the next couple of commits.

**Comment by kingsofcoms** [comment]
Yes, i found the -ss --save-segments option in --help yesterday, its very helpful option. How i'm using MUGEN is calculate the bpm of my music, create a metronome track with exact bpm but 1.5-2x the length. This gives me extra video segments because around 10-15% clips are not what i need and if i rerun the script 2nd time it give me completely new clips. But i really liked some clips from 1st run and now 2nd run has repeats from 1st run.

So i try to get clips by using extra audio length, this way i can remove clips i dont need and still have enough clips to work with these clips also appear in sequence to the story. Then i can just concatenate the entire folder. (Though i'm using a simple editor program)
