### ISSUE TITLE
the progress_bar issue

### ISSUE THREAD

**Issue by dixonja** [scherroman/mugen#21]
Thanks for the code firstly, but I constantly got the errors for TypeError:write_videofile() got an unexpected keyword argument 'progress_bar'. I don't know how to solve this issue.

**Comment by scherroman** [comment]
Hey dixonja, thanks for reporting this. Try pip installing moviepy==0.2.3.5 instead if you have 1.0.0 installed, as I believe I saw this issue when using the latest release of moviepy. Looks like pip installs moviepy 1.0.0 when asking for >=0.2.3.5 even though its a major version above, so I'll lock this down in the environment.
