### ISSUE TITLE
Building wheel for Pillow (setup.py) ... error

### ISSUE THREAD

**Issue by fpcarva** [scherroman/mugen#24]
When I run  pip install -e mugen in anaconda I recive this message: 

Building wheel for Pillow (setup.py) ... error

"The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source."

**Comment by scherroman** [comment]
Hey @fpcarva!

Not sure what's causing that exactly, but it may be related to [a bad pip version](https://github.com/python-pillow/Pillow/issues/4242)? I just updated the Pillow version to `8.2.0` to deal with some security vulnerability reported by dependabot, so you may want to try upgrading your pip as well and try again. For reference I was able to do a working clean install with `pip install -e mugen`  in a python 3.7 conda environment with pip `21.0.1` and conda `4.3.30`.

If you're still having issues let me know your OS/OS version, conda version (if you're using it), python version, and pip version for reference
