### ISSUE TITLE
Build on MacBook Air with an M1

### ISSUE THREAD

**Issue by Atomic-Germ** [scherroman/mugen#38]
It won't build (well, work) on MacOS, no matter how I install libsndfile it can't be found.

**Comment by scherroman** [comment]
Thanks for reporting this @Atomic-Germ, I'm not seeing any issues on my mac or the continuous integration for macOS, but those are both running on Intel chips, so there may be an issue with installing dependencies on Apple chips. Unfortunately I don't currently have an M1/M2 to test on and Github Actions doesn't yet support M1/M2, so I don't have an easy way to dig into this at the moment. Though it could be possible to manually look into this on a cloud provider that supports M1/M2 instances and even use a [self-hosted runner](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) for continuous integration if the provider has a free tier for open source. In the meantime could you provide some more details on your system and the errors you get when trying to install based on the [bug issue template](https://github.com/scherroman/mugen/issues/new?assignees=&labels=bug&template=bug_report.md&title=)?

**Comment by shaunsaker** [comment]
FYI I just tried this on my Mac M1 using the [installation steps](https://github.com/scherroman/mugen#installation) and it's working 👍

**Comment by scherroman** [comment]
@shaunsaker glad to hear it!
