### ISSUE TITLE
Make text detection optional

### ISSUE THREAD

**Issue by scherroman** [scherroman/mugen#7]
Mugen should exclude text detection if tesserocr is not pip installed.
If tesserocr is pip installed, Mugen should use text detection by default.

**Comment by sethcohn** [comment]
I'd actually prefer an argument option to disable.  Perhaps even on a video by video basis in the json.

**Comment by scherroman** [comment]
This issue is mainly intended to allow Mugen to work out of the box without extra external dependencies.

#### As of commit b2a38a9 in new_mugen, you can also disable filters via option
```
python cli.py create --exclude-video-filters not_has_text
```
You could even make a music video using only clips with text
```
python cli.py create --video-filters has_text
```

As for control on a video-per-video basis, that's definitely on the roadmap.
